### PR TITLE
update version of grunt-sync

### PR DESCRIPTION
**Pull request by semy**

### CODE REVIEW

**Comment by mikermcneil** [comment]
@semy thanks!  Would you recreate the shrinkwrap file?  Also, would you mind looping in some other folks from the community to test this out and be sure it works properly and is backwards-compatible?  We've had to be incredibly delicate w/ grunt plugin versions in the past :/

**Comment by patricksimpson** [comment]
On node 10.11.0
We're getting the error using grunt-sass:  `Warning: Cannot read property 'bigint' of undefined`
When using this PR fork, the problem is resolved.  
Related: https://github.com/gruntjs/grunt/issues/1645

**Comment by idhard** [comment]
hey @mikermcneil  FYI the package [grunt-sync](https://github.com/tomusdrw/grunt-sync) has a deprecation notice....

**Comment by johnabrams7** [comment]
@semy @patricksimpson @idhard - Hey everyone, grunt-sync has now been updated.

**Review by mikermcneil — APPROVED** [review]
lgtm, although there's a new version out so going to try that -- also will need to update shrinkwrap

**Comment by mikermcneil** [comment]
see also https://github.com/balderdashy/sails/issues/4470

**Pull request merged**
